# # config file version
apiVersion: 1

# # list of datasources that should be deleted from the database
# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Stand-Demo-JMeter
    orgId: 1
  - name: JMeter
    orgId: 1

# # list of datasources to insert/update depending
# # on what's available in the database
datasources:
   # <string, required> name of the datasource. Required
 - name: JMeter
   # <string, required> datasource type. Required
   type: influxdb
   # <string, required> access mode. direct or proxy. Required
   access: proxy
   # <int> org id. will default to orgId 1 if not specified
   orgId: 1   
   # <string> url
   url: http://influxdb:8086
   # <string> database name, if used
   database: jmeter
   # <bool> allow users to edit datasources from the UI.
   editable: false
   # <bool> enable/disable basic auth
   basicAuth: false
   # <string> basic auth username
   basicAuthUser: readuser
   # <string> json object of data that will be encrypted.
   jsonData:
     httpMode: POST
     maxSeries: 300
     timeInterval: 60s
   secureJsonData:
     # <string> basic auth password
     basicAuthPassword: password
